### ISSUE TITLE
Forwarding if successful

### ISSUE THREAD

**Issue by Witti2** [richardhj/contao-ajax_reload_element#18]
Hello, I re-activated the extension because I want to use it for the login. Everything also works perfectly, if the entries are incorrect, but if the customer logs in with his correct data, then the page specified in the module is not forwarded, but you stay on the current page and see your login.

Am I doing something wrong or does the script ignore the successful login and the forwarding specified in the module?

greetings

**Comment by richardhj** [comment]
See #20
