### ISSUE TITLE
No checkbox "Allow ajax reload" in Contao 4.9.x

### ISSUE THREAD

**Issue by jankout** [richardhj/contao-ajax_reload_element#19]
Hello,

unfortunately, I cannot find any checkbox "Allow ajax reload". Neither in element nor modules in back end. 

Could you check it, please? Thank you.

Best wishes, J.

**Comment by fritzmg** [comment]
@jankout are you sure that the checkbox is missing on _all_ content elements and modules? But in any case, the issue is likely fixed by https://github.com/richardhj/contao-ajax_reload_element/pull/21

**Comment by richardhj** [comment]
Thanks to @fritzmg :-)

**Comment by jankout** [comment]
Thank. It works. :-)
