### ISSUE TITLE
Forwarding does not work

### ISSUE THREAD

**Issue by Witti2** [richardhj/contao-ajax_reload_element#20]
Hello, we have the problem that with the login form that the redirect page is ignored by the extension when the login is successful. It would be nice that if the login was successful, the forwarding page specified in the backend for the login is taken over and the user is also directed there.

We had written this before, but it doesn't work with the current version either.

If that is not possible, please give us a short info, then we would uninstall the extension again.

greetings

**Comment by richardhj** [comment]
The forwarding happens in the JS snippet client-side by means of the HTTP response code, so please have a look in the dev-tools and check the requests :-) 

https://github.com/richardhj/contao-ajax_reload_element/blob/be80d50b8a6a9638ab1381e3c64e3a97d157c130/src/Resources/public/jquery.ajax-reload-form.js#L31
