### ISSUE TITLE
ce_* elements in tl_news are not recognized.

### ISSUE THREAD

**Issue by reluem** [richardhj/contao-ajax_reload_element#9]
Hi, 
first of all I love the simplicity of this module. Thank you!

When using content elements in tl_news such as a gallery, it is not recognized correctly. 
My gallery as a news item has e.g. the following identifier `data-ajax-reload-element="mod::1240"`

This is probably due to this line here, since the ptable of my gallery is not tl_article.
https://github.com/richardhj/contao-ajax_reload_element/blob/3b158123a3602322317311da1e64128aa5921f4e/src/EventListener/AjaxReloadElementListener.php#L58

Thank you!

**Comment by richardhj** [comment]
True, we don’t support the “dynamicPtable” of the tl_content table atm. 
I’ll look into it.

**Comment by richardhj** [comment]
I applied a fix in 1ab0c6c31a857baffaedbd9e605db99b464a19b4.
Can you please install `dev-master as 2.1.4` of this package and give feedback?

**Comment by reluem** [comment]
Hi, 
tested the new dev-master and it works now for content elements in tl_news.
Ajax gallery reloading 🥇
